name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Remove shallow
        # run: git fetch --prune --unshallow
        run: git fetch --depth=10000

      - name: Build the Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker build . --file Dockerfile --tag novaticss/microservice-image-base:1

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login docker.io

      - name: Push Docker image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker push novaticss/microservice-image-base:1
